# Generated by Django 2.0.4 on 2018-04-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='ip',
            new_name='System',
        ),
    ]
